language: objective-c
before_install:
- gem install cocoapods -v '0.34.4'
- pod install
script:
- xctool -workspace MyTodoList.xcworkspace -scheme MyTodoList -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace MyTodoList.xcworkspace -scheme MyTodoList -destination 'platform=iOS
  Simulator,name=iPhone 6' test
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
after_success:
- chmod 755 slac.sh
- ./slack.sh
notifications:
  slack:
    secure: Gn8o+F4UucliwjHwIxSsCTKWSX13ptMnhllkx37fh9lJnymvHoT/Po8u0lHmsGDwD5QgxcVf/UtH/OJcmTIaEhi5XcUEF3edWJcD/L3QHuWPvMFU5+JVGRy62Qf094UdwEbS69tkzdhOvvDMbVrMW+m+JFuszFXLBYs2gCgCq14=
