language: objective-c
before_install:
- gem install cocoapods -v '0.34.4'
- pod install
script:
- xctool -workspace MyTodoList.xcworkspace -scheme MyTodoList -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace MyTodoList.xcworkspace -scheme MyTodoList -destination 'platform=iOS
  Simulator,name=iPhone 6' test
after_success:
- chmod 755 chatwork.sh
- ./slack.sh
notifications:
  slack:
    secure: iGT5vxadnF1Nun9HLVXWz7iXmLwsGKwHpGSg96oo97HvduNR8BBS5/FmLR+0nQNXXrmTEYqTtbW/t1JFGSCJWPiJbNYOLA0AwY3DcHPOrNFF/0Yv3O19pokmAcVrlQnFfzsiC7fGCbDHaqLonfwZbFJltO9QjiWjuZXF+F+vJSw=
